export type Lang = "en" | "mr";

/* ── Site-wide copy ─────────────────────────────────────────────────── */
export const CONTENT = {
  en: {
    headerBadge: "Maharashtra",
    toggleTo: "मराठी",
    comingSoon: "Coming Soon",
    heroTitle: ["Maharashtra's Property", "Services Platform"],
    heroDesc:
      "One platform for Stamp Duty, 7/12 records, and Property Tax — built for Maharashtra, available in English and Marathi.",
    tryCalculator: "Stamp Duty Calculator →",
    servicesTitle: "Our Services",
    servicesSubtitle: "15 tools to simplify property ownership in Maharashtra.",
    footerBrand: "Mudrankseva",
    footerRights: "All rights reserved.",
    footerTagline: "Maharashtra · Stamp Duty · 7/12 Records · Property Tax",
    calc: {
      pageTitle: "Stamp Duty Calculator",
      subtitle: "Instant calculations per Maharashtra 2026 rates",
      backHome: "← Home",
      propValue: "Property Value",
      propValuePlaceholder: "Enter amount",
      district: "District",
      districtSearch: "Search district…",
      districtNone: "No districts found.",
      areaType: "Area Type",
      areaTypes: {
        corporation: "Municipal Corporation",
        council: "Municipal Council / Cantonment",
        rural: "Rural / Gram Panchayat",
      },
      gender: "Buyer",
      genders: { male: "Male / Joint", female: "Female" },
      surveyNo: "Survey / Gat Number",
      surveyPlaceholder: "Optional",
      resultTitle: "Breakdown",
      resultEmpty:
        "Enter property details above to see your stamp duty estimate.",
      propValueLabel: "Property Value",
      baseStampDuty: "Base Stamp Duty",
      metroCess: "Metro Cess",
      lbt: "Local Body Tax",
      stampDutyTotal: "Total Stamp Duty",
      regFee: "Registration Fee",
      regFeeCap: "capped at ₹30,000",
      grandTotal: "Total Payable",
      femaleNote: "Female buyer — 1% rebate on base duty",
      rateNote: "Rates per Maharashtra 2026 schedule.",
      disclaimer:
        "Estimate only. Consult a registered sub-registrar or professional before transacting.",
      areaLabel: "Built-up Area",
      areaPlaceholder: "e.g. 1200",
      rateLabel: "Rate per sqm (₹)",
      switchToManual: "Enter value manually",
      quickEstimateLabel: "Quick Estimate",
      calculateBtn: "Calculate",
      leadSaved: "Saved",
      verifyBtn: "Verify on Official IGR Portal →",
      disclaimer2: "By using this tool, you agree to our terms of data processing.",
      rateNote2026:
        "Rates updated for FY 2026-27 (Unchanged as per Govt. Notification dated Mar 31, 2026).",
      enterValue: "Enter Market Value",
      fromArea: "Area × Rate",
      unitLabel: "Unit",
      units: { sqmt: "Sq. Meter", sqft: "Sq. Foot", guntha: "Guntha", acre: "Acre" },
    },
  },
  mr: {
    headerBadge: "महाराष्ट्र",
    toggleTo: "English",
    comingSoon: "लवकरच येत आहे",
    heroTitle: ["महाराष्ट्राचे मालमत्ता", "सेवा व्यासपीठ"],
    heroDesc:
      "मुद्रांक शुल्क, ७/१२ उतारा आणि मालमत्ता कर — एकाच व्यासपीठावर, इंग्रजी व मराठीत उपलब्ध.",
    tryCalculator: "मुद्रांक शुल्क कॅल्क्युलेटर →",
    servicesTitle: "आमच्या सेवा",
    servicesSubtitle: "महाराष्ट्रातील मालमत्ता मालकी सुलभ करण्यासाठी १५ साधने.",
    footerBrand: "मुद्रांकसेवा",
    footerRights: "सर्व हक्क राखीव.",
    footerTagline: "महाराष्ट्र · मुद्रांक शुल्क · ७/१२ उतारा · मालमत्ता कर",
    calc: {
      pageTitle: "मुद्रांक शुल्क कॅल्क्युलेटर",
      subtitle: "महाराष्ट्र २०२६ दरांनुसार त्वरित गणना",
      backHome: "← मुख्यपृष्ठ",
      propValue: "मालमत्ता मूल्य",
      propValuePlaceholder: "रक्कम प्रविष्ट करा",
      district: "जिल्हा",
      districtSearch: "जिल्हा शोधा…",
      districtNone: "जिल्हा आढळला नाही.",
      areaType: "क्षेत्र प्रकार",
      areaTypes: {
        corporation: "महानगरपालिका",
        council: "नगरपालिका / छावणी",
        rural: "ग्रामीण / ग्रामपंचायत",
      },
      gender: "खरेदीदार",
      genders: { male: "पुरुष / संयुक्त", female: "महिला" },
      surveyNo: "सर्व्हे / गट नंबर",
      surveyPlaceholder: "ऐच्छिक",
      resultTitle: "तपशील",
      resultEmpty: "मुद्रांक शुल्क अंदाज पाहण्यासाठी वरील तपशील भरा.",
      propValueLabel: "मालमत्ता मूल्य",
      baseStampDuty: "मूळ मुद्रांक शुल्क",
      metroCess: "मेट्रो उपकर",
      lbt: "स्थानिक संस्था कर",
      stampDutyTotal: "एकूण मुद्रांक शुल्क",
      regFee: "नोंदणी शुल्क",
      regFeeCap: "कमाल ₹३०,०००",
      grandTotal: "एकूण देय",
      femaleNote: "महिला खरेदीदार — मूळ शुल्कावर १% सवलत",
      rateNote: "महाराष्ट्र २०२६ अनुसूचीनुसार दर.",
      disclaimer:
        "हे केवळ अंदाज आहे. व्यवहारापूर्वी नोंदणीकृत दुय्यम निबंधक किंवा व्यावसायिकाचा सल्ला घ्या.",
      areaLabel: "बांधकाम क्षेत्र",
      areaPlaceholder: "उदा. १२००",
      rateLabel: "दर प्रति चौ.मी. (₹)",
      switchToManual: "मूल्य स्वतः प्रविष्ट करा",
      quickEstimateLabel: "त्वरित अंदाज",
      calculateBtn: "गणना करा",
      leadSaved: "जतन केले",
      verifyBtn: "अधिकृत IGR पोर्टलवर सत्यापित करा →",
      disclaimer2:
        "हे साधन वापरून, तुम्ही आमच्या डेटा प्रक्रिया अटींशी सहमत आहात.",
      rateNote2026:
        "FY 2026-27 साठी दर अद्ययावत (दि. ३१ मार्च २०२६ च्या शासन अधिसूचनेनुसार अपरिवर्तित).",
      enterValue: "बाजार मूल्य प्रविष्ट करा",
      fromArea: "क्षेत्र × दर",
      unitLabel: "एकक",
      units: { sqmt: "चौ. मीटर", sqft: "चौ. फूट", guntha: "गुंठा", acre: "एकर" },
    },
  },
} as const;

/* ── 36 Maharashtra Districts ───────────────────────────────────────── */
export const DISTRICTS: { en: string; mr: string }[] = [
  { en: "Ahmednagar", mr: "अहमदनगर" },
  { en: "Akola", mr: "अकोला" },
  { en: "Amravati", mr: "अमरावती" },
  { en: "Chhatrapati Sambhajinagar", mr: "छत्रपती संभाजीनगर" },
  { en: "Beed", mr: "बीड" },
  { en: "Bhandara", mr: "भंडारा" },
  { en: "Buldhana", mr: "बुलढाणा" },
  { en: "Chandrapur", mr: "चंद्रपूर" },
  { en: "Dhule", mr: "धुळे" },
  { en: "Gadchiroli", mr: "गडचिरोली" },
  { en: "Gondia", mr: "गोंदिया" },
  { en: "Hingoli", mr: "हिंगोली" },
  { en: "Jalgaon", mr: "जळगाव" },
  { en: "Jalna", mr: "जालना" },
  { en: "Kolhapur", mr: "कोल्हापूर" },
  { en: "Latur", mr: "लातूर" },
  { en: "Mumbai City", mr: "मुंबई शहर" },
  { en: "Mumbai Suburban", mr: "मुंबई उपनगर" },
  { en: "Nagpur", mr: "नागपूर" },
  { en: "Nanded", mr: "नांदेड" },
  { en: "Nandurbar", mr: "नंदुरबार" },
  { en: "Nashik", mr: "नाशिक" },
  { en: "Dharashiv", mr: "धाराशिव" },
  { en: "Palghar", mr: "पालघर" },
  { en: "Parbhani", mr: "परभणी" },
  { en: "Pune", mr: "पुणे" },
  { en: "Raigad", mr: "रायगड" },
  { en: "Ratnagiri", mr: "रत्नागिरी" },
  { en: "Sangli", mr: "सांगली" },
  { en: "Satara", mr: "सातारा" },
  { en: "Sindhudurg", mr: "सिंधुदुर्ग" },
  { en: "Solapur", mr: "सोलापूर" },
  { en: "Thane", mr: "ठाणे" },
  { en: "Wardha", mr: "वर्धा" },
  { en: "Washim", mr: "वाशीम" },
  { en: "Yavatmal", mr: "यवतमाळ" },
];

/* ── 15 Feature cards ───────────────────────────────────────────────── */
export const FEATURES = [
  {
    titleEn: "Stamp Duty Calculator",
    titleMr: "मुद्रांक शुल्क कॅल्क्युलेटर",
    descEn: "Instantly calculate registration fees and duty based on current Maharashtra rates.",
    descMr: "महाराष्ट्रातील चालू दरांनुसार नोंदणी शुल्क आणि मुद्रांक शुल्काची त्वरित गणना करा.",
  },
  {
    titleEn: "Market Value Finder",
    titleMr: "बाजार मूल्य शोधक",
    descEn: "Find the official Ready Reckoner rates for any property in Pune and Maharashtra.",
    descMr: "पुणे आणि महाराष्ट्रातील कोणत्याही मालमत्तेचे अधिकृत रेडी रेकनर दर शोधा.",
  },
  {
    titleEn: "7/12 Health Check",
    titleMr: "७/१२ आरोग्य तपासणी",
    descEn: "AI-powered title verification and litigation risk analysis.",
    descMr: "एआय-आधारित मालकी हक्क पडताळणी आणि कायदेशीर जोखीम विश्लेषण.",
  },
  {
    titleEn: "Gazette Name Change",
    titleMr: "राजपत्र नाव बदल",
    descEn: "Fully automated process for legal name changes in the Official Gazette.",
    descMr: "अधिकृत राजपत्रात कायदेशीर नाव बदलण्यासाठी पूर्णपणे स्वयंचलित प्रक्रिया.",
  },
  {
    titleEn: "Automated Deed Drafting",
    titleMr: "स्वयंचलित दस्तऐवज मसुदा",
    descEn: "Generate error-free Sale, Gift, and Release deeds in minutes.",
    descMr: "विक्री, बक्षीस आणि मुक्ती पत्रे काही मिनिटांत त्रुटीमुक्त तयार करा.",
  },
  {
    titleEn: "Digital Rent Agreement",
    titleMr: "डिजिटल भाडे करार",
    descEn: "Legally binding registered rent agreements without visiting the office.",
    descMr: "कार्यालयात न जाता कायदेशीररीत्या नोंदणीकृत भाडे करार तयार करा.",
  },
  {
    titleEn: "Vertical Property Card",
    titleMr: "उर्ध्व मालमत्ता पत्रक",
    descEn: "Management and tracking for urban apartment property cards.",
    descMr: "शहरी अपार्टमेंट मालमत्ता पत्रकांचे व्यवस्थापन आणि ट्रॅकिंग.",
  },
  {
    titleEn: "Mutation (Ferfar) Alerts",
    titleMr: "फेरफार सूचना",
    descEn: "Get real-time updates when any change occurs in your 7/12 extract.",
    descMr: "तुमच्या ७/१२ उतार्‍यात कोणताही बदल झाल्यास रिअल-टाइम अपडेट्स मिळवा.",
  },
  {
    titleEn: "Property Tax Transfer",
    titleMr: "मालमत्ता कर हस्तांतरण",
    descEn: "Automated assistant for transferring tax records to new owners.",
    descMr: "नवीन मालकांच्या नावे कर नोंदणी हस्तांतरित करण्यासाठी स्वयंचलित सहाय्यक.",
  },
  {
    titleEn: "Public Notice AI",
    titleMr: "सार्वजनिक नोटिस एआय",
    descEn: "Generate and schedule legal notices for newspapers instantly.",
    descMr: "वर्तमानपत्रांसाठी कायदेशीर नोटिसा त्वरित तयार करा आणि शेड्यूल करा.",
  },
  {
    titleEn: "Certified Valuation",
    titleMr: "प्रमाणित मूल्यांकन",
    descEn: "Get professional market valuation reports for bank and legal use.",
    descMr: "बँक आणि कायदेशीर वापरासाठी व्यावसायिक बाजार मूल्य अहवाल मिळवा.",
  },
  {
    titleEn: "Index-II Retrieval",
    titleMr: "इंडेक्स-II उपलब्धी",
    descEn: "Fast digital access to historical property registration records.",
    descMr: "ऐतिहासिक मालमत्ता नोंदणी कागदपत्रांमध्ये जलद डिजिटल प्रवेश.",
  },
  {
    titleEn: "Society NOC Portal",
    titleMr: "सोसायटी ना-हरकत पोर्टल",
    descEn: "Automated requests for society transfer and no-objection certificates.",
    descMr: "सोसायटी हस्तांतरण आणि ना-हरकत प्रमाणपत्रांसाठी स्वयंचलित विनंती पोर्टल.",
  },
  {
    titleEn: "Heirship Assistant",
    titleMr: "वारसा सहाय्यक",
    descEn: "Documentation support for legal heirship and succession certificates.",
    descMr: "कायदेशीर वारसा आणि उत्तराधिकार प्रमाणपत्रांसाठी कागदपत्रे सहाय्य.",
  },
  {
    titleEn: "Adjudication Tracker",
    titleMr: "निर्धारण ट्रॅकर",
    descEn: "Real-time status tracking for pending adjudication cases.",
    descMr: "प्रलंबित मुद्रांक शुल्क निर्धारण प्रकरणांचा रिअल-टाइम स्टेटस ट्रॅकर.",
  },
] as const;
