import { jsPDF } from "jspdf";

/* ── Types ── */
export interface CalcResult {
  propValue: number;
  isFemale: boolean;
  baseRate: number;
  baseAmt: number;
  metroCessAmt: number | null;
  lbtAmt: number | null;
  totalDutyRate: number;
  totalDutyAmt: number;
  regFeeAmt: number;
  regFeeCapped: boolean;
  grandTotal: number;
}

export interface ReportInput {
  name: string;
  phone: string;
  result: CalcResult;
  district: string | null;
  areaType: "corporation" | "council" | "rural";
  gender: "male" | "female";
  surveyNo: string;
  propValue: number;
  lang: string;
}

/* ── Brand colours ── */
const OXBLOOD      = [74,  18,  18]  as const;  // #4a1212
const OXBLOOD_MID  = [112, 28,  28]  as const;  // #701c1c
const GOLD         = [212, 175, 55]  as const;  // #d4af37
const GOLD_MUTED   = [180, 148, 40]  as const;
const CREAM        = [253, 248, 240] as const;  // #fdf8f0
const INK          = [26,  5,   5]   as const;  // #1a0505
const GREY         = [100, 80,  80]  as const;
const LIGHT_GREY   = [220, 210, 210] as const;

/* ── Currency formatter ──
   jsPDF Helvetica covers WinAnsiEncoding (Latin-1 only).
   U+20B9 RUPEE SIGN is outside that range, so we use "Rs." for reliable
   rendering. Devanagari labels are handled via Noto Sans Devanagari when
   the font is available (see loadDevanagariFont). */
const fmt = (n: number) =>
  "Rs. " + n.toLocaleString("en-IN", { maximumFractionDigits: 0 });

const pct = (r: number) => `${(r * 100).toFixed(0)}%`;

/* ── Label dictionaries ── */
const L = {
  en: {
    reportTitle:   "Stamp Duty Calculation Report",
    reckoner:      "Maharashtra Ready Reckoner 2026-27",
    preparedFor:   "Prepared for",
    propDetails:   "Property Details",
    propValue:     "Property Value",
    district:      "District",
    areaType:      "Area Type",
    buyerType:     "Buyer Type",
    female:        "Female (Concessional Rate)",
    male:          "Male",
    surveyNo:      "Survey / Gat No.",
    stampDuty:     "Stamp Duty Breakdown",
    baseStamp:     "Base Stamp Duty",
    metroCess:     "Metro Cess",
    lbt:           "Local Body Tax / LBT",
    totalStamp:    "Total Stamp Duty",
    regCharges:    "Registration Charges",
    regFee:        "Registration Fee",
    regCapped:     "capped at Rs. 30,000",
    grandTotal:    "TOTAL AMOUNT PAYABLE",
    savingsTip:    "Savings Tip:",
    savingsBody:
      "Female buyers may be eligible for 1% reduced stamp duty. Consider " +
      "registering in a female family member's name to save on total charges.",
    disclaimer:
      "* Rates as per Maharashtra Ready Reckoner 2026-27. Actual rates may vary " +
      "— verify with the Sub-Registrar's office before payment. " +
      "* Female buyers may be eligible for reduced stamp duty in certain municipalities. " +
      "* Registration fee is 1% of property value, capped at Rs. 30,000.",
    upsellTitle:  "Need a Rent Agreement?",
    upsellBody:
      "Generate your Maharashtra Leave & License Agreement at " +
      "mudrankseva.in/rent-agreement for just Rs. 299. Ready in 5 minutes.",
    footer:
      "Generated by Mudrankseva  \xB7  mudrankseva.in  \xB7  Maharashtra Property Services",
    corp:    "Municipal Corporation",
    council: "Municipal Council / Cantonment",
    rural:   "Gram Panchayat / Rural",
    fileTag: "stamp_duty",
  },
  mr: {
    reportTitle:   "मुद्रांक शुल्क गणना अहवाल",
    reckoner:      "महाराष्ट्र रेडी रेकनर 2026-27",
    preparedFor:   "यांच्यासाठी तयार",
    propDetails:   "मालमत्तेचा तपशील",
    propValue:     "मालमत्तेचे मूल्य",
    district:      "जिल्हा",
    areaType:      "क्षेत्र प्रकार",
    buyerType:     "खरेदीदाराचा प्रकार",
    female:        "महिला (सवलत दर)",
    male:          "पुरुष",
    surveyNo:      "सर्व्हे / गट क्र.",
    stampDuty:     "मुद्रांक शुल्काचा तपशील",
    baseStamp:     "मूळ मुद्रांक शुल्क",
    metroCess:     "मेट्रो उपकर",
    lbt:           "स्थानिक स्वराज्य संस्था कर / LBT",
    totalStamp:    "एकूण मुद्रांक शुल्क",
    regCharges:    "नोंदणी शुल्क",
    regFee:        "नोंदणी शुल्क",
    regCapped:     "कमाल रु. ३०,०००",
    grandTotal:    "एकूण देय रक्कम",
    savingsTip:    "बचत टीप:",
    savingsBody:
      "महिला खरेदीदारांना 1% कमी मुद्रांक शुल्काची सूट मिळू शकते. " +
      "एकूण शुल्क वाचवण्यासाठी महिला कुटुंब सदस्याच्या नावे नोंदणी करण्याचा विचार करा.",
    disclaimer:
      "* दर महाराष्ट्र रेडी रेकनर 2026-27 नुसार आहेत. प्रत्यक्ष दर वेगळे असू शकतात " +
      "— देय करण्यापूर्वी दुय्यम निबंधक कार्यालयाकडे सत्यापित करा. " +
      "* महिला खरेदीदारांना काही नगरपालिकांमध्ये कमी मुद्रांक शुल्क मिळू शकते. " +
      "* नोंदणी शुल्क मालमत्तेच्या मूल्याच्या 1% असते, कमाल रु. ३०,०००.",
    upsellTitle:  "भाडे करार हवा आहे?",
    upsellBody:
      "mudrankseva.in/rent-agreement वर फक्त रु. 299 मध्ये महाराष्ट्र Leave & License करार तयार करा. 5 मिनिटांत तयार.",
    footer:
      "Mudrankseva द्वारे तयार  \xB7  mudrankseva.in  \xB7  Maharashtra Property Services",
    corp:    "महानगरपालिका",
    council: "नगरपालिका / छावणी",
    rural:   "ग्रामपंचायत / ग्रामीण",
    fileTag: "mudrank_shulk",
  },
} as const;

/* ── Devanagari font loader ──
   Place NotoSansDevanagari-Regular.ttf in public/fonts/ to enable Marathi
   PDF labels. Falls back to English labels silently if the file is absent. */
async function loadDevanagariFont(doc: jsPDF): Promise<boolean> {
  try {
    const res = await fetch("/fonts/NotoSansDevanagari-Regular.ttf");
    if (!res.ok) return false;
    const buf = await res.arrayBuffer();
    const bytes = new Uint8Array(buf);
    let binary = "";
    const chunk = 8192;
    for (let i = 0; i < bytes.length; i += chunk)
      binary += String.fromCharCode(...bytes.slice(i, Math.min(i + chunk, bytes.length)));
    const b64 = btoa(binary);
    doc.addFileToVFS("NotoSansDevanagari.ttf", b64);
    doc.addFont("NotoSansDevanagari.ttf", "NotoSansDevanagari", "normal");
    doc.addFont("NotoSansDevanagari.ttf", "NotoSansDevanagari", "bold");
    return true;
  } catch {
    return false;
  }
}

export async function generateStampDutyReport(input: ReportInput): Promise<void> {
  const { name, phone, result, district, areaType, gender, surveyNo, lang } = input;
  const isMr = lang === "mr";

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const W   = 210;
  const M   = 16;
  const CW  = W - 2 * M;
  let y     = 0;

  /* ── Load Devanagari font if Marathi mode; fall back to English labels if absent */
  let mrFont = false;
  if (isMr) mrFont = await loadDevanagariFont(doc);

  // Labels follow lang; font quality degrades gracefully but labels always match
  const t        = isMr ? L.mr : L.en;
  const fontName = mrFont ? "NotoSansDevanagari" : "helvetica";
  const sf       = (bold = false) => doc.setFont(fontName, bold ? "bold" : "normal");

  /* ── Colour helpers ── */
  const fill = (...c: readonly [number, number, number]) => doc.setFillColor(c[0], c[1], c[2]);
  const tc   = (...c: readonly [number, number, number]) => doc.setTextColor(c[0], c[1], c[2]);
  const draw = (...c: readonly [number, number, number]) => doc.setDrawColor(c[0], c[1], c[2]);

  const hline = (yy: number) => {
    draw(...LIGHT_GREY);
    doc.setLineWidth(0.2);
    doc.line(M, yy, W - M, yy);
  };

  const sectionHeader = (title: string) => {
    fill(...OXBLOOD_MID);
    doc.rect(M, y, CW, 7, "F");
    tc(...GOLD);
    sf(true);
    doc.setFontSize(7.5);
    doc.text(title.toUpperCase(), M + 3, y + 5);
    y += 11;
  };

  const dataRow = (label: string, value: string, bold = false, shade = false) => {
    if (shade) {
      fill(245, 240, 235);
      doc.rect(M, y - 3, CW, 7, "F");
    }
    sf(bold);
    doc.setFontSize(9.5);
    tc(...INK);
    doc.text(label, M + 3, y + 1);
    doc.setFont("helvetica", bold ? "bold" : "normal"); // values always in Helvetica
    doc.text(value, W - M - 3, y + 1, { align: "right" });
    y += 7;
  };

  /* ════════════════════════════════════════════════════
     HEADER BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(0, 0, W, 42, "F");

  fill(...GOLD);
  doc.rect(0, 42, W, 1.2, "F");

  tc(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("MUDRANKSEVA", M, 17);

  tc(...GOLD_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text("mudrankseva.in  \xB7  Maharashtra Property Services", M, 24);

  tc(255, 255, 255);
  sf(true);
  doc.setFontSize(13);
  doc.text(t.reportTitle, M, 35);

  const date = new Date().toLocaleDateString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
  });
  tc(...GOLD_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(date, W - M, 35, { align: "right" });

  tc(180, 150, 150);
  doc.setFontSize(7.5);
  doc.text(t.reckoner, W - M, 24, { align: "right" });

  y = 50;

  /* ── Prepared for ── */
  tc(...GREY);
  sf(false);
  doc.setFontSize(9);
  doc.text(
    `${t.preparedFor}: ${name}${phone ? "  \xB7  +91 " + phone : ""}`,
    M, y,
  );
  y += 10;

  /* ════════════════════════════════════════════════════
     PROPERTY DETAILS
  ════════════════════════════════════════════════════ */
  sectionHeader(t.propDetails);

  const areaTypeLabel =
    areaType === "corporation" ? t.corp
    : areaType === "council"   ? t.council
    :                            t.rural;

  dataRow(t.propValue, fmt(result.propValue), true);
  if (district) dataRow(t.district, district, false, true);
  dataRow(t.areaType, areaTypeLabel, false, !district);
  dataRow(t.buyerType, result.isFemale ? t.female : t.male, false, true);
  if (surveyNo) dataRow(t.surveyNo, surveyNo);

  y += 3;

  /* ════════════════════════════════════════════════════
     STAMP DUTY BREAKDOWN
  ════════════════════════════════════════════════════ */
  sectionHeader(t.stampDuty);

  dataRow(`${t.baseStamp} (${pct(result.baseRate)})`, fmt(result.baseAmt));
  if (result.metroCessAmt !== null)
    dataRow(`${t.metroCess} (1%)`, fmt(result.metroCessAmt), false, true);
  if (result.lbtAmt !== null)
    dataRow(`${t.lbt} (1%)`, fmt(result.lbtAmt), false, result.metroCessAmt === null);

  hline(y + 1);
  y += 5;
  dataRow(`${t.totalStamp} (${pct(result.totalDutyRate)})`, fmt(result.totalDutyAmt), true);

  y += 4;
  sectionHeader(t.regCharges);
  dataRow(
    `${t.regFee} (1%${result.regFeeCapped ? `, ${t.regCapped}` : ""})`,
    fmt(result.regFeeAmt),
  );

  y += 5;

  /* ════════════════════════════════════════════════════
     GRAND TOTAL BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(M, y, CW, 16, "F");

  tc(...GOLD);
  sf(true);
  doc.setFontSize(10);
  doc.text(t.grandTotal.toUpperCase(), M + 5, y + 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(fmt(result.grandTotal), W - M - 5, y + 10.5, { align: "right" });

  y += 23;

  /* ════════════════════════════════════════════════════
     SAVINGS TIP — male buyers only
  ════════════════════════════════════════════════════ */
  if (!result.isFemale) {
    fill(255, 251, 232);
    draw(...GOLD);
    doc.setLineWidth(0.5);
    doc.roundedRect(M, y, CW, 17, 2, 2, "FD");

    tc(...OXBLOOD_MID);
    sf(true);
    doc.setFontSize(8.5);
    doc.text(t.savingsTip, M + 4, y + 7);

    tc(80, 50, 30);
    sf(false);
    doc.setFontSize(8);
    const tipLines = doc.splitTextToSize(t.savingsBody, CW - 8);
    doc.text(tipLines, M + 4, y + 13);
    y += 22;
  }

  y += 3;

  /* ════════════════════════════════════════════════════
     DISCLAIMER
  ════════════════════════════════════════════════════ */
  hline(y);
  y += 5;

  tc(...GREY);
  sf(false);
  doc.setFontSize(7);
  const disclaimerLines = doc.splitTextToSize(t.disclaimer, CW);
  doc.text(disclaimerLines, M, y);
  y += disclaimerLines.length * 3.8 + 5;

  /* ════════════════════════════════════════════════════
     UPSELL CARD
  ════════════════════════════════════════════════════ */
  fill(...CREAM);
  draw(...GOLD);
  doc.setLineWidth(0.4);
  doc.roundedRect(M, y, CW, 18, 2, 2, "FD");

  tc(...OXBLOOD_MID);
  sf(true);
  doc.setFontSize(9);
  doc.text(t.upsellTitle, M + 4, y + 7);

  tc(80, 50, 30);
  sf(false);
  doc.setFontSize(8);
  const upsellLines = doc.splitTextToSize(t.upsellBody, CW - 8);
  doc.text(upsellLines, M + 4, y + 13);

  /* ════════════════════════════════════════════════════
     FOOTER BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(0, 284, W, 13, "F");

  fill(...GOLD);
  doc.rect(0, 284, W, 0.8, "F");

  tc(...GOLD_MUTED);
  sf(false);
  doc.setFontSize(7.5);
  doc.text(t.footer, W / 2, 292, { align: "center" });

  /* ── Save ── */
  const safeName = name.replace(/[^\w\s]/g, "").replace(/\s+/g, "_").toLowerCase() || "client";
  doc.save(`mudrankseva_${t.fileTag}_${safeName}.pdf`);
}
