import { jsPDF } from "jspdf";

/* ── Types ── */
export interface CalcResult {
  propValue: number;
  isFemale: boolean;
  baseRate: number;
  baseAmt: number;
  metroCessAmt: number | null;
  lbtAmt: number | null;
  totalDutyRate: number;
  totalDutyAmt: number;
  regFeeAmt: number;
  regFeeCapped: boolean;
  grandTotal: number;
}

export interface ReportInput {
  name: string;
  phone: string;
  result: CalcResult;
  district: string | null;
  areaType: "corporation" | "council" | "rural";
  gender: "male" | "female";
  surveyNo: string;
  propValue: number;
  lang: string;
}

/* ── Brand colours ── */
const OXBLOOD      = [74,  18,  18]  as const;
const OXBLOOD_MID  = [112, 28,  28]  as const;
const GOLD         = [212, 175, 55]  as const;
const GOLD_MUTED   = [180, 148, 40]  as const;
const CREAM        = [253, 248, 240] as const;
const INK          = [26,  5,   5]   as const;
const GREY         = [100, 80,  80]  as const;
const LIGHT_GREY   = [220, 210, 210] as const;

/* ── Currency formatter ──
   jsPDF Helvetica covers WinAnsiEncoding (Latin-1 only).
   U+20B9 RUPEE SIGN is outside that range, so we use "Rs." */
const fmt = (n: number) =>
  "Rs. " + n.toLocaleString("en-IN", { maximumFractionDigits: 0 });

const pct = (r: number) => `${(r * 100).toFixed(0)}%`;

/* ── English-only labels (jsPDF cannot render Devanagari script) ── */
const L = {
  reportTitle:   "Stamp Duty Calculation Report",
  reckoner:      "Maharashtra Ready Reckoner 2026-27",
  preparedFor:   "Prepared for",
  propDetails:   "Property Details",
  propValue:     "Property Value",
  district:      "District",
  areaType:      "Area Type",
  buyerType:     "Buyer Type",
  female:        "Female (Concessional Rate)",
  male:          "Male",
  surveyNo:      "Survey / Gat No.",
  stampDuty:     "Stamp Duty Breakdown",
  baseStamp:     "Base Stamp Duty",
  metroCess:     "Metro Cess",
  lbt:           "Local Body Tax / LBT",
  totalStamp:    "Total Stamp Duty",
  regCharges:    "Registration Charges",
  regFee:        "Registration Fee",
  regCapped:     "capped at Rs. 30,000",
  grandTotal:    "TOTAL AMOUNT PAYABLE",
  savingsTip:    "Savings Tip:",
  savingsBody:
    "Female buyers may be eligible for 1% reduced stamp duty. Consider " +
    "registering in a female family member's name to save on total charges.",
  disclaimer:
    "* Rates as per Maharashtra Ready Reckoner 2026-27. Actual rates may vary " +
    "— verify with the Sub-Registrar's office before payment. " +
    "* Female buyers may be eligible for reduced stamp duty in certain municipalities. " +
    "* Registration fee is 1% of property value, capped at Rs. 30,000.",
  upsellTitle:  "Need a Rent Agreement?",
  upsellBody:
    "Generate your Maharashtra Leave & License Agreement at " +
    "mudrankseva.in/rent-agreement for just Rs. 299. Ready in 5 minutes.",
  footer:
    "Generated by Mudrankseva  \xB7  mudrankseva.in  \xB7  Maharashtra Property Services",
  corp:    "Municipal Corporation",
  council: "Municipal Council / Cantonment",
  rural:   "Gram Panchayat / Rural",
};

export async function generateStampDutyReport(input: ReportInput): Promise<void> {
  const { name, phone, result, district, areaType, gender, surveyNo, lang } = input;
  const isMr = lang === "mr";

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const W   = 210;
  const M   = 16;
  const CW  = W - 2 * M;
  let y     = 0;

  const sf = (bold = false) => doc.setFont("helvetica", bold ? "bold" : "normal");

  /* ── Colour helpers ── */
  const fill = (...c: readonly [number, number, number]) => doc.setFillColor(c[0], c[1], c[2]);
  const tc   = (...c: readonly [number, number, number]) => doc.setTextColor(c[0], c[1], c[2]);
  const draw = (...c: readonly [number, number, number]) => doc.setDrawColor(c[0], c[1], c[2]);

  const hline = (yy: number) => {
    draw(...LIGHT_GREY);
    doc.setLineWidth(0.2);
    doc.line(M, yy, W - M, yy);
  };

  const sectionHeader = (title: string) => {
    fill(...OXBLOOD_MID);
    doc.rect(M, y, CW, 7, "F");
    tc(...GOLD);
    sf(true);
    doc.setFontSize(7.5);
    doc.text(title.toUpperCase(), M + 3, y + 5);
    y += 11;
  };

  const dataRow = (label: string, value: string, bold = false, shade = false) => {
    if (shade) {
      fill(245, 240, 235);
      doc.rect(M, y - 3, CW, 7, "F");
    }
    sf(bold);
    doc.setFontSize(9.5);
    tc(...INK);
    doc.text(label, M + 3, y + 1);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(value, W - M - 3, y + 1, { align: "right" });
    y += 7;
  };

  /* ════════════════════════════════════════════════════
     HEADER BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(0, 0, W, 42, "F");

  fill(...GOLD);
  doc.rect(0, 42, W, 1.2, "F");

  tc(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("MUDRANKSEVA", M, 17);

  tc(...GOLD_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text("mudrankseva.in  \xB7  Maharashtra Property Services", M, 24);

  tc(255, 255, 255);
  sf(true);
  doc.setFontSize(13);
  doc.text(L.reportTitle, M, 35);

  const date = new Date().toLocaleDateString("en-IN", {
    day: "2-digit", month: "short", year: "numeric",
  });
  tc(...GOLD_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(date, W - M, 35, { align: "right" });

  tc(180, 150, 150);
  doc.setFontSize(7.5);
  doc.text(L.reckoner, W - M, 24, { align: "right" });

  y = 50;

  /* ── Prepared for ── */
  tc(...GREY);
  sf(false);
  doc.setFontSize(9);
  doc.text(
    `${L.preparedFor}: ${name}${phone ? "  \xB7  +91 " + phone : ""}`,
    M, y,
  );
  y += 7;

  /* ── Marathi language note ── */
  if (isMr) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(120, 80, 80);
    doc.text(
      "* Report generated in English as Marathi PDF fonts are not supported by your browser.",
      M, y,
    );
    y += 8;
  } else {
    y += 3;
  }

  /* ════════════════════════════════════════════════════
     PROPERTY DETAILS
  ════════════════════════════════════════════════════ */
  sectionHeader(L.propDetails);

  const areaTypeLabel =
    areaType === "corporation" ? L.corp
    : areaType === "council"   ? L.council
    :                            L.rural;

  dataRow(L.propValue, fmt(result.propValue), true);
  if (district) dataRow(L.district, district, false, true);
  dataRow(L.areaType, areaTypeLabel, false, !district);
  dataRow(L.buyerType, result.isFemale ? L.female : L.male, false, true);
  if (surveyNo) dataRow(L.surveyNo, surveyNo);

  y += 3;

  /* ════════════════════════════════════════════════════
     STAMP DUTY BREAKDOWN
  ════════════════════════════════════════════════════ */
  sectionHeader(L.stampDuty);

  dataRow(`${L.baseStamp} (${pct(result.baseRate)})`, fmt(result.baseAmt));
  if (result.metroCessAmt !== null)
    dataRow(`${L.metroCess} (1%)`, fmt(result.metroCessAmt), false, true);
  if (result.lbtAmt !== null)
    dataRow(`${L.lbt} (1%)`, fmt(result.lbtAmt), false, result.metroCessAmt === null);

  hline(y + 1);
  y += 5;
  dataRow(`${L.totalStamp} (${pct(result.totalDutyRate)})`, fmt(result.totalDutyAmt), true);

  y += 4;
  sectionHeader(L.regCharges);
  dataRow(
    `${L.regFee} (1%${result.regFeeCapped ? `, ${L.regCapped}` : ""})`,
    fmt(result.regFeeAmt),
  );

  y += 5;

  /* ════════════════════════════════════════════════════
     GRAND TOTAL BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(M, y, CW, 16, "F");

  tc(...GOLD);
  sf(true);
  doc.setFontSize(10);
  doc.text(L.grandTotal.toUpperCase(), M + 5, y + 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(fmt(result.grandTotal), W - M - 5, y + 10.5, { align: "right" });

  y += 23;

  /* ════════════════════════════════════════════════════
     SAVINGS TIP — male buyers only
  ════════════════════════════════════════════════════ */
  if (!result.isFemale) {
    fill(255, 251, 232);
    draw(...GOLD);
    doc.setLineWidth(0.5);
    doc.roundedRect(M, y, CW, 17, 2, 2, "FD");

    tc(...OXBLOOD_MID);
    sf(true);
    doc.setFontSize(8.5);
    doc.text(L.savingsTip, M + 4, y + 7);

    tc(80, 50, 30);
    sf(false);
    doc.setFontSize(8);
    const tipLines = doc.splitTextToSize(L.savingsBody, CW - 8);
    doc.text(tipLines, M + 4, y + 13);
    y += 22;
  }

  y += 3;

  /* ════════════════════════════════════════════════════
     DISCLAIMER
  ════════════════════════════════════════════════════ */
  hline(y);
  y += 5;

  tc(...GREY);
  sf(false);
  doc.setFontSize(7);
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, CW);
  doc.text(disclaimerLines, M, y);
  y += disclaimerLines.length * 3.8 + 5;

  /* ════════════════════════════════════════════════════
     UPSELL CARD
  ════════════════════════════════════════════════════ */
  fill(...CREAM);
  draw(...GOLD);
  doc.setLineWidth(0.4);
  doc.roundedRect(M, y, CW, 18, 2, 2, "FD");

  tc(...OXBLOOD_MID);
  sf(true);
  doc.setFontSize(9);
  doc.text(L.upsellTitle, M + 4, y + 7);

  tc(80, 50, 30);
  sf(false);
  doc.setFontSize(8);
  const upsellLines = doc.splitTextToSize(L.upsellBody, CW - 8);
  doc.text(upsellLines, M + 4, y + 13);

  /* ════════════════════════════════════════════════════
     FOOTER BAND
  ════════════════════════════════════════════════════ */
  fill(...OXBLOOD);
  doc.rect(0, 284, W, 13, "F");

  fill(...GOLD);
  doc.rect(0, 284, W, 0.8, "F");

  tc(...GOLD_MUTED);
  sf(false);
  doc.setFontSize(7.5);
  doc.text(L.footer, W / 2, 292, { align: "center" });

  /* ── Save ── */
  const fileTag  = isMr ? "mudrank_shulk" : "stamp_duty";
  const safeName = name.replace(/[^\w\s]/g, "").replace(/\s+/g, "_").toLowerCase() || "client";
  doc.save(`mudrankseva_${fileTag}_${safeName}.pdf`);
}
